/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CheckinButton: typeof import('./src/components/CheckinButton.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    FaveButton: typeof import('./src/components/FaveButton.vue')['default']
    Group: typeof import('./src/components/Group.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloCard: typeof import('./src/components/HelloCard.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    ItemGetter: typeof import('./src/components/ItemGetter.vue')['default']
    ItemLoader: typeof import('./src/components/ItemLoader.vue')['default']
    LoginButton: typeof import('./src/components/LoginButton.vue')['default']
    NavList: typeof import('./src/components/NavList.vue')['default']
    NewPropose: typeof import('./src/components/NewPropose.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    ProposeEdit: typeof import('./src/components/ProposeEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceName: typeof import('./src/components/SourceName.vue')['default']
    UploadButton: typeof import('./src/components/UploadButton.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBottomNavigation: typeof import('vuetify/lib')['VBottomNavigation']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCarousel: typeof import('vuetify/lib')['VCarousel']
    VCarouselItem: typeof import('vuetify/lib')['VCarouselItem']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VContent: typeof import('vuetify/lib')['VContent']
    VDatePicker: typeof import('vuetify/lib')['VDatePicker']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFlex: typeof import('vuetify/lib')['VFlex']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VRow: typeof import('vuetify/lib')['VRow']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VTimePicker: typeof import('vuetify/lib')['VTimePicker']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}
